n = (input('Digite algo: '))

print(type(n))
print('É um número?', n.isnumeric())
print('É uma letra?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Só tem espaços?', n.isspace())
print('Está em maiúsculo?', n.isupper())
print('Está em minúsculo?', n.islower())
print('Está capitalizado?', n.istitle())